# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build and Release
on:
  push:
    branches:
      - dev
      - 'port/**'
      - 'workflow/**'
    tags:
      - 'v3/**'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Commit hash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          else
            COMMIT_SHA=${GITHUB_SHA}
          fi
          echo "SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Java ${{ matrix.java }} setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        if: runner.os == 'Linux'
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle build
        run: ./gradlew build

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: "extrasounds-dev+${{env.SHORT_SHA}}"
          path: build/libs/

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}